[package]
name = "file-picker-android"
version = "0.1.2"
edition = "2021"
links = "file-picker-android"

[dependencies]
serde = "1"
tauri = "2.0.0-beta.2"

[build-dependencies]
tauri-plugin = { version = "2.0.0-beta.1", features = ["build"] }
