[package]
name = "file-picker-android"
version = "0.1.1"
edition = "2021"
links = "file-picker-android"

[dependencies]
serde = "1"
tauri = "2.0.0-alpha.9"

[build-dependencies]
tauri-build = "2.0.0-alpha.5"
